---



---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-demo-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/bogiepam/argocd-example-apps
    targetRevision: HEAD
    path: sync-waves/sync-demo-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
