apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-wave-app-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/bogiepam/argocd-example-apps
    targetRevision: HEAD
    path: sync-waves/sync-demo-apps/production
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: false
      prune: false
      allowEmpty: false